const doctorsData = [
  // Neurologists
 {
  id: 1,
  imageUri: "/images/d1.jpg",
  name: "Dr. Maya Iyer",
  specialisation: "Neurologist",
  experience: "1 year",
  address: "Bordowali, Agartala",
  rating: 3,
},

  {
    id: 2,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Arjun Menon",
    specialisation: "Neurologist",
    experience: "5 years",
    address: "Indira Nagar, Bangalore",
    rating: 4,
  },
  {
    id: 3,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Sneha Kapoor",
    specialisation: "Neurologist",
    experience: "8 years",
    address: "South City, Kolkata",
    rating: 5,
  },
  {
    id: 4,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Ravi Shah",
    specialisation: "Neurologist",
    experience: "10 years",
    address: "Salt Lake, Kolkata",
    rating: 5,
  },

  // Endocrinologists
  {
    id: 5,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Kavita Reddy",
    specialisation: "Endocrinologist",
    experience: "4 years",
    address: "Lake Road, Mumbai",
    rating: 4,
  },
  {
    id: 6,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Rajat Singh",
    specialisation: "Endocrinologist",
    experience: "6 years",
    address: "Sector 12, Chandigarh",
    rating: 5,
  },
  {
    id: 7,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Neha Vyas",
    specialisation: "Endocrinologist",
    experience: "3 years",
    address: "Civil Lines, Jaipur",
    rating: 3,
  },
  {
    id: 8,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Karan Patel",
    specialisation: "Endocrinologist",
    experience: "7 years",
    address: "MG Road, Delhi",
    rating: 4,
  },

  // Cardiologists
  {
    id: 9,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Sameer Khanna",
    specialisation: "Cardiologist",
    experience: "7 years",
    address: "Park Street, Kolkata",
    rating: 5,
  },
  {
    id: 10,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Sneha Verma",
    specialisation: "Cardiologist",
    experience: "8 years",
    address: "Lake Avenue, Chennai",
    rating: 5,
  },
  {
    id: 11,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Ramesh Iyer",
    specialisation: "Cardiologist",
    experience: "6 years",
    address: "DLF Phase 2, Gurgaon",
    rating: 4,
  },
  {
    id: 12,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Meena Joshi",
    specialisation: "Cardiologist",
    experience: "10 years",
    address: "Sector 21, Noida",
    rating: 5,
  },

  // Dermatologists
  {
    id: 13,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Sunita Paul",
    specialisation: "Dermatologist",
    experience: "6 years",
    address: "MG Road, Bangalore",
    rating: 4,
  },
  {
    id: 14,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Priya Sen",
    specialisation: "Dermatologist",
    experience: "5 years",
    address: "Salt Lake, Kolkata",
    rating: 4,
  },
  {
    id: 15,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Rahul Gupta",
    specialisation: "Dermatologist",
    experience: "8 years",
    address: "Fort Road, Pune",
    rating: 5,
  },
  {
    id: 16,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Rekha Sharma",
    specialisation: "Dermatologist",
    experience: "3 years",
    address: "Indira Nagar, Bangalore",
    rating: 3,
  },

  // Pulmonologists
  {
    id: 17,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Ajay Mehta",
    specialisation: "Pulmonologist",
    experience: "8 years",
    address: "Gariahat, Kolkata",
    rating: 5,
  },
  {
    id: 18,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Varun Malhotra",
    specialisation: "Pulmonologist",
    experience: "7 years",
    address: "Connaught Place, Delhi",
    rating: 4,
  },
  {
    id: 19,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Sheela Rao",
    specialisation: "Pulmonologist",
    experience: "6 years",
    address: "Banjara Hills, Hyderabad",
    rating: 4,
  },
  {
    id: 20,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Snehal Desai",
    specialisation: "Pulmonologist",
    experience: "5 years",
    address: "Anna Nagar, Chennai",
    rating: 4,
  },

  // Gastroenterologists
  {
    id: 21,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Priya Sharma",
    specialisation: "Gastroenterologist",
    experience: "10 years",
    address: "Connaught Place, Delhi",
    rating: 5,
  },
  {
    id: 22,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Ravi Mehta",
    specialisation: "Gastroenterologist",
    experience: "8 years",
    address: "Lake Avenue, Chennai",
    rating: 4,
  },
  {
    id: 23,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Sneha Kapoor",
    specialisation: "Gastroenterologist",
    experience: "6 years",
    address: "Salt Lake, Kolkata",
    rating: 5,
  },
  {
    id: 24,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Rajat Verma",
    specialisation: "Gastroenterologist",
    experience: "7 years",
    address: "Anna Nagar, Chennai",
    rating: 5,
  },

  // Rheumatologists
  {
    id: 25,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Rohit Sen",
    specialisation: "Rheumatologist",
    experience: "5 years",
    address: "Anna Nagar, Chennai",
    rating: 4,
  },
  {
    id: 26,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Seema Verma",
    specialisation: "Rheumatologist",
    experience: "7 years",
    address: "Park Street, Kolkata",
    rating: 5,
  },
  {
    id: 27,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Kunal Patel",
    specialisation: "Rheumatologist",
    experience: "8 years",
    address: "Indira Nagar, Bangalore",
    rating: 4,
  },
  {
    id: 28,
    imageUri: "https://via.placeholder.com/150",
    name: "Dr. Swati Kapoor",
    specialisation: "Rheumatologist",
    experience: "6 years",
    address: "DLF Phase 3, Gurgaon",
    rating: 4,
  },
];

export default doctorsData;
